# Generated by Django 3.2 on 2021-04-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_new_vocab', '0002_rename_new_word_vocabwords_vocab_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VocabWords',
            new_name='VocabWord',
        ),
    ]
