# Generated by Django 3.2 on 2021-04-27 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_new_vocab', '0003_rename_vocabwords_vocabword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabword',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 19, 8, 25, 853743, tzinfo=utc)),
        ),
    ]
