# Generated by Django 3.2 on 2021-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_new_vocab', '0006_alter_vocabword_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabword',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
